--- コマンド DDL
-- クリエト アルタ ヅロプ

CREATE DATABASE PRIMEIRODB;

USE PRIMEIRODB;

CREATE TABLE ALUNO (
	ID学生 INT PRIMARY KEY IDENTITY(1,1),
	学生のNAME VARCHAR(80),
	性別 CHAR (1),
	生年月日 DATE,

);

ALTER TABLE ALUNO ADD CPF CHAR(14) NOT NULL; -- CPF カラクタ/ 00000000000 (11) / 000.000.000-00 (14)

ALTER TABLE ALUNO ADD シチュエーション VARCHAR(7) NOT NULL -- アクティブ (ON) / デザクティブ (OFF)

ALTER TABLE ALUNO ADD CONSTRAINT CK_ALUNOSIT
	CHECK (シチュエーション IN ('ON','OFF'));
ALTER TABLE ALUNO ADD CONSTRAINT CK_ALUNOSEXO
	CHECK (性別 IN ('M','F'));

-- コマンド DQL
-- セレクト
SELECT * FROM ALUNO;

INSERT INTO ALUNO (学生のNAME, 性別, 生年月日, シチュエーション, CPF)
		VALUES ('Saito Kenji', 'M', '11-22-2003','OFF','696.969.696-69');

-- アイ スピク エングリシュ